export const AUTH_ERROR_CODES = {
  INVALID_STUDENT_ID: 'INVALID_STUDENT_ID',
  LOGIN_FAILED: 'LOGIN_FAILED',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
