export const SAVED_TOPICS_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  DATABASE_ERROR: 'DATABASE_ERROR',
  FORBIDDEN: 'FORBIDDEN',
} as const;

export type SavedTopicsErrorCode =
  (typeof SAVED_TOPICS_ERROR_CODES)[keyof typeof SAVED_TOPICS_ERROR_CODES];
