import type { AnalysisData, VerifiedDataSource, VerifiedReference } from '@/types';

interface FormatAnalysisParams {
  topicTitle: string;
  country: string;
  issue: string;
  interest: string;
  analysis: AnalysisData;
  verifiedDataSources?: VerifiedDataSource[];
  verifiedReferences?: VerifiedReference[];
}

export function formatAnalysisAsText({
  topicTitle,
  country,
  issue,
  interest,
  analysis,
  verifiedDataSources = [],
  verifiedReferences = [],
}: FormatAnalysisParams): string {
  const lines: string[] = [];

  lines.push(`# ${topicTitle}`);
  lines.push(`Country: ${country} | Issue: ${issue}`);
  lines.push(`Area of Interest: ${interest}`);
  lines.push('');

  lines.push('## Rationale');
  lines.push(`Relevance: ${analysis.rationale.relevance}`);
  lines.push(`Feasibility: ${analysis.rationale.feasibility}`);
  lines.push(`Impact: ${analysis.rationale.impact}`);
  lines.push('');

  lines.push('## Key Policy Questions');
  analysis.policy_questions.forEach((q, i) => {
    lines.push(`${i + 1}. ${q}`);
  });
  lines.push('');

  lines.push('## Recommended Methodologies');
  analysis.methodologies.forEach((m) => {
    lines.push(`- ${m.methodology}: ${m.explanation}`);
  });
  lines.push('');

  if (verifiedDataSources.length > 0) {
    lines.push('## Verified Data Sources');
    verifiedDataSources.forEach((s) => {
      lines.push(`- ${s.name}: ${s.url}`);
      lines.push(`  ${s.description}`);
    });
    lines.push('');
  }

  if (verifiedReferences.length > 0) {
    lines.push('## Verified References');
    verifiedReferences.forEach((r) => {
      const authorsStr = r.authors.length > 0 ? `${r.authors.join(', ')} (${r.year})` : '';
      const urlStr = r.url ? ` - ${r.url}` : '';
      lines.push(`- ${r.title}${authorsStr ? ` | ${authorsStr}` : ''}${urlStr}`);
    });
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by Capstone Topic Explorer');

  return lines.join('\n');
}
